# Generated by Django 6.0.7 on 2026-08-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preset_image',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
