# Generated by Django 6.0.7 on 2026-09-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_conversation_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='is_archived',
            new_name='user_one_archived',
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_two_archived',
            field=models.BooleanField(default=False),
        ),
    ]
