# Generated by Django 6.0.7 on 2026-08-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
